### ISSUE TITLE
hook.sh: line 30: zones: unbound variable

### ISSUE THREAD

**Issue by m0len** [sineverba/cfhookbash#105]
After running this `./dehydrated -c -t dns-01 -k '/root/cfhookbash/hook.sh'`, I got this:

```
/root/cfhookbash/hook.sh: line 30: zones: unbound variable
ERROR: deploy_challenge hook returned with non-zero exit code
```

`config.sh` is set, `api_token` and `zones` are set and correct.

**Comment by m0len** [comment]
Btw, I used wildcard domains, maybe that's related. After removing wildcard domains, it worked fine.

**Comment by sineverba** [comment]
I did never try with wildacard only, but only with 

```
example.com www.example.com
home.example.net *.home.example.net
```
(see README).

Can you share your configuration, more similar than possible to reality (masking of course sensible data)?

**Comment by m0len** [comment]
With a `domains.txt` like below, it won't work

```
*.example.com > star_example_com
```

But with a `domains.txt` like this, it works

```
example.com *.example.com
```

**Comment by m0len** [comment]
Additionally, with a `domains.txt` like below and a `config.sh` like below, it won't work either

```
*.example.com > star_example_com
```

```
case ${1} in
        "star_example_com")
                api_token="xyzxyzxyzxyzxyzxyzxyzxyzxyzxyzxyzxyzxyzxyz"
                zones="zyxzyxzyxzyxzyxzyxzyxzyxzyxzyxzyxzyx"
        ;;

esac
```

**Comment by sineverba** [comment]
Yes, I had troubles with "star_example_com" domain. Use first example, without the `>` sign. Is it applicable to your case?

**Comment by m0len** [comment]
But according to https://github.com/dehydrated-io/dehydrated/blob/master/docs/domains_txt.md

  > "Certificates with a wildcard domain as the first (or only) name require an alias to be set."

So the `>` sign is a must, or maybe a better workaround is using the second example, the certs are the same with using only wildcard domains, I think. (`certs` folder structure should be identical)

**Comment by sineverba** [comment]
`cfhookbash` is an "extension", a hook for `dehydrated`. So, with my hook, atm it is not possible run differently from the examples shown on my README.
Try with `example.com *.example.com` and lmk if it works for your case.

**Comment by m0len** [comment]
I have tried with `example.com *.example.com`, and yes, it works. 
Then I use the cert signed in this way for my subdomain `s.example.com` and it works well, so I guess your hook can be used to sign a wildcard? I am using Caddy as web server.

**Comment by sineverba** [comment]
Yes, it is expected to work.
