### ISSUE TITLE
deploy_cert should respect ROOT_DIR env var

### ISSUE THREAD

**Issue by Ramblurr** [sineverba/cfhookbash#15]
https://github.com/sineverba/cfhookbash/blob/master/hook.sh#L100

When using ROOT_DIR, the deploy_cert doesn't use it, and thus can't find the deploy config.

**Comment by sineverba** [comment]
Did you create a deploy.sh in same folder of cfhookbash? There is a starting script to rename (deploy.config.sh to deploy.sh)

I will investigate ASAP.

**Comment by Ramblurr** [comment]
See [this line in deploy_cert](https://github.com/sineverba/cfhookbash/blob/master/hook.sh#L100)

This line needs to be changed to the following, to bring it in line with all the other functions:
```
    if [[ -z "${ROOT_DIR}" ]];then
        rootDirectory="${PWD}/hooks/cfhookbash";
    else
        rootDirectory="${ROOT_DIR}";
fi
```

**Comment by sineverba** [comment]
I can verify. I will publish hotfix ASAP. Thank you!
