### ISSUE TITLE
Diff for the correct deletion of both TXT records.

### ISSUE THREAD

**Issue by vladonv** [sineverba/cfhookbash#32]
--- ./hook.sh   2019-09-24 16:56:33.000000000 +0000
+++ ./hook.sh.new       2019-10-31 19:34:59.297281909 +0000
@@ -26,7 +26,7 @@
         -H "X-Auth-Key: ${global_api_key}"\
         -H "Content-Type: application/json"\
         --data '{"type":"TXT","name":"'${prefix}${1}'","content":"'${3}'","ttl":120,"priority":10,"proxied":false}'\
-        -o "${rootDirectory}/${1}.txt"
+        -o "${rootDirectory}/${1}.${2}.txt"
 
     # Add delay to get the new DNS record
     local DELAY=60;
@@ -69,7 +69,7 @@
         rootDirectory="${ROOT_DIR}";
     fi
 
-    key_value=$(grep -Po '"id":.*?[^\\]"' "${rootDirectory}/${1}.txt")
+    key_value=$(grep -Po '"id":.*?[^\\]"' "${rootDirectory}/${1}.${2}.txt")
     #printf "id: %s\n" "${key_value}"
     #Remove first 6 occurence
     id="${key_value:6}"
@@ -83,7 +83,7 @@
      -H "X-Auth-Key: ${global_api_key}"\
      -H "Content-Type: application/json"
 
-     rm "${rootDirectory}/${1}.txt"
+     rm "${rootDirectory}/${1}.${2}.txt"
 
     # This hook is called after attempting to validate each domain,
     # whether or not validation was successful. Here you can delete

**Comment by sineverba** [comment]
Thank you for your time to open this issue. Can you explain better and, send a PR against `develop` branch with expalain of what are you trying to solve?

**Comment by sineverba** [comment]
I'm closing for no answer. If need, feel free to reopen.
