### ISSUE TITLE
ERROR: clean_challenge hook returned with non-zero exit code

### ISSUE THREAD

**Issue by GTAXL** [sineverba/cfhookbash#36]
Hello, I'm trying to issue certs but keep getting these errors.

 + Responding to challenge for excession.gtaxl.net authorization...
 + Cleaning challenge tokens...
hooks/cfhookbash/hook.sh: line 78: -1: substring expression < 0
ERROR: clean_challenge hook returned with non-zero exit code

and in the text file

{"success":false,"errors":[{"code":7003,"message":"Could not route to \/zones\/dns_records, perhaps your object identifier is invalid?"},{"code":7000,"message":"No route for that URI"}],"messages":[],"result":null}

**Comment by sineverba** [comment]
Hello,
1) Set in main config file of dehydrates stage env:
```bash
CA="https://acme-staging-v02.api.letsencrypt.org/directory"
```
2) Run from command line `./dehydrated -c -t dns-01 -x -k 'hooks/cfhookbash/hook.sh'`

3) Check the `zone` value. I got your same error with 

```bash
case ${1} in
	"subdomain.domain.it")
		global_api_key="I_PUT_A_RIGHT_VALUE_HERE"
		zones="I_PUT_A_WRONG_VALUE_HERE"
		email="myemail@example.com"
	;;
esac

```

```bash
{
	"success": false,
	"errors": [{
		"code": 7003,
		"message": "Could not route to \/zones\/I_PUT_A_WRONG_VALUE_HERE\/dns_records, perhaps your object identifier is invalid?"
	}, {
		"code": 7000,
		"message": "No route for that URI"
	}],
	"messages": [],
	"result": null
}
```

And (note zones is empty)

```bash
case ${1} in
	"subdomain.domain.it")
		global_api_key="I_PUT_A_RIGHT_VALUE_HERE"
		zones=""
		email="myemail@example.com"
	;;
esac

```

```bash
{"success":false,"errors":[{"code":7003,"message":"Could not route to \/zones\/dns_records, perhaps your object identifier is invalid?"},{"code":7000,"message":"No route for that URI"}],"messages":[],"result":null}
```

**Comment by GTAXL** [comment]
Hello, it was certainly NOT my zone ID. The problem was the case statement. I removed the case statement from the config.sh to set the variables globally, as I issue all the sub-domains under the same domain, I guess I could put a wildcard. Your documentation says to just put www.example.com when in reality you should show *.example.com and example.com.

The certs were successfully deployed after I fixed the case statement. However your script still has issues, when cleaning the challenge tokens I get,

 + Challenge is valid!
 + Cleaning challenge tokens...
{
  "code": 1001,
  "error": "method_not_allowed"
}
{
  "code": 1001,
  "error": "method_not_allowed"
}


I check my CloudFlare account, and the acme challenge TXT records are still there! Not good... Here is a picture, http://pik.gtaxl.net/07_05_20_08_03_21.png

**Comment by sineverba** [comment]
I will check. Got error in stage environment or also with production?

For case issues, if I did understand correctly your usage, you could put every domain/subdomain there. Yes, probably a bit repeat, I need to try wildcards also.

I can confirm that my case works, I use it for my domains and subs by the way... ;-)

**Comment by GTAXL** [comment]
Production, and the example config.sh shows www.example.com, so naturally I put www.gtaxl.net but I'm issuing lots of subdomains under gtaxl.net, so in reality there should be two case statements, *.gtaxl.net and gtaxl.net, or get rid of the case statement entirely. Having to put the same API key hundreds of times for lots of subdomains is silly and inconvenient.

I also noticed the deploy hook didn't execute, I'll have to investigate that. I do some bash work myself, so I should of known better on the case statement, but your documentation could be clearer.

**Comment by sineverba** [comment]
I can confirm the error. Placing a patch to solve it. I don't know what's (if) changed from Cloudflare side.
