### ISSUE TITLE
Delay for propogation

### ISSUE THREAD

**Issue by WayneManion** [sineverba/cfhookbash#4]
Hello. I used your script the other night to get my SSL setup going. I did have to make one change, though.

I got failure after failure running the script as delivered. When I added a 10-second delay in the dehydrated script in between sending the DNS-01 string and the verification step it worked on the first try. 

I suggested adding an option for this delay on the dehydrated github issues forum, but it was suggested that this feature be added on a per-host-script basis. 

https://github.com/lukas2511/dehydrated/issues/579#issuecomment-406813511

**Comment by sineverba** [comment]
Hi,
I saw other issue. Need to investigate.
Could you share how you did edit the script?

**Comment by WayneManion** [comment]
I added 

'sleep 10'

right after (line 782):

'  # Validate pending challenges'

**Comment by WayneManion** [comment]
`  # Validate pending challenges
  local idx=0
  echo " + Waiting 10 seconds. (WMM)"
  sleep 10
  while [ ${idx} -lt ${num_pending_challenges} ]; do
    echo " + Responding to challenge for ${challenge_names[${idx}]} authorization..."`

**Comment by sineverba** [comment]
I will try. In all my tests, I never got this issue. Cloudflare is very fast. Probably a network issue, but I will investigate. One question: how many domains did you try to secure at same time?

**Comment by WayneManion** [comment]
I was initially trying with two domains, but I cut it down to one at a time after I repeatedly had problems.
