### ISSUE TITLE
Error code 1001, method_not_allowed

### ISSUE THREAD

**Issue by GTAXL** [sineverba/cfhookbash#67]
I ran the script once, got that error. Downloaded latest version and did a -x to force dehydrated to renew as it somehow thinks the certs were extended when they weren't. I get the same error, method_not_allowed after downloading latest hook.sh.

**Comment by sineverba** [comment]
Do you have jq installed?

**Comment by GTAXL** [comment]
Yes I do.

root@jetstream:~# apt-cache policy jq
jq:
  Installed: 1.5+dfsg-2+b1
  Candidate: 1.5+dfsg-2+b1
  Version table:
 *** 1.5+dfsg-2+b1 500
        500 http://ftp.us.debian.org/debian buster/main amd64 Packages
        100 /var/lib/dpkg/status

**Comment by GTAXL** [comment]
It seems to happen at the cleaning challenge tokens stage. Which messes with the rest of the script and doesn't run the deploy script.

 + Responding to challenge for golden.gtaxl.net authorization...
 + Challenge is valid!
 + Responding to challenge for golden.server.gtaxl.net authorization...
 + Challenge is valid!
 + Cleaning challenge tokens...
id: null
{
  "code": 1001,
  "error": "method_not_allowed"
}
id: null
{
  "code": 1001,
  "error": "method_not_allowed"
}
id: null
{
  "code": 1001,
  "error": "method_not_allowed"
}

**Comment by sineverba** [comment]
Preamble: I'm moving from old house to new one, so it is a bit difficult for me to do several tests.
By the way, I did installed a fresh Ubuntu in VirtualBox, so I started with a freshly downloaded dehydrated and cfhookbash.

```
#
# !! WARNING !! No main config file found, using default config!
#
Processing www.-------.it
 + Checking domain name(s) of existing cert... unchanged.
 + Checking expire date of existing cert...
 + Valid till Nov  4 17:49:22 2020 GMT (Longer than 30 days). Ignoring because renew was forced!
 + Signing domains...
 + Generating private key...
 + Generating signing request...
 + Requesting new certificate order from CA...
 + Received 1 authorizations URLs from the CA
 + Handling authorization for www.------.it
 + 1 pending challenge(s)
 + Deploying challenge tokens...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   656    0   510  100   146    433    124  0:00:01  0:00:01 --:--:--   557
+++ Wait for 10 seconds. +++
 + Responding to challenge for www.------.it authorization...
 + Challenge is valid!
 + Cleaning challenge tokens...
id: b----------------------
{"result":{"id":"b--------"},"success":true,"errors":[],"messages":[]} + Requesting certificate...
 + Checking certificate...
 + Done!
 + Creating fullchain.pem...
 + Done!
```

In effect, that "id: null" probably cannot get the ID from the file. Can you see if script writes a file .txt into the directory of cfhookbash? Why you have 3 errors if domain is only one? Do you have some error in config.sh file?

Please, try to restart from zero. Last version has changed a bit.

**Comment by GTAXL** [comment]
I think I fixed it, the certs actually did renew, the deploy script didn't execute though due to that error. I saw in Cloudflare DNS that all the challenge tokens were still there, so I deleted them then re-ran the script and it worked with no error. So I'm guessing it didn't like the challenge tokens being left over from the first run.
